<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>Billboard</AssemblyName>
    <RootNamespace>LISSTech.Billboard.Host</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../LISSTech.Billboard/LISSTech.Billboard.csproj" />
  </ItemGroup>
</Project>
